name: voz_plena
description: "Voz Plena â€“ AnÃ¡lisis de voz y frecuencia"
publish_to: "none"
version: 1.0.0+1

environment:
    sdk: ^3.9.2

dependencies:
    flutter:
        sdk: flutter
    shared_preferences: ^2.3.2

    cupertino_icons: ^1.0.8
    record: ^6.1.2 # ğŸ™ grabaciÃ³n moderna
    scidart: ^0.0.2-dev.12 # ğŸ”¢ FFT y procesamiento matemÃ¡tico estable
    fl_chart: ^1.1.1 # ğŸ“ˆ grÃ¡fico dinÃ¡mico
    path_provider: ^2.1.5
    flutter_audio_capture: ^1.1.11
    permission_handler: ^12.0.1
    go_router: ^16.2.4 # ğŸ§­ navegaciÃ³n moderna
    rename: ^3.1.0
    flutter_launcher_icons: ^0.14.4
    flutter_native_splash: ^2.4.6
    tflite_flutter: ^0.12.1
    intl: ^0.20.2
    flutter_sound: ^9.28.0
    firebase_core: ^4.2.1
    firebase_auth: ^6.1.2
    cloud_firestore: ^6.1.0

dev_dependencies:
    flutter_test:
        sdk: flutter
    flutter_lints: ^6.0.0

flutter:
    uses-material-design: true
    assets:
        - assets/icon/logo.png
        - assets/icon/logoo-splash.png
        - assets/stories/
        - assets/images/
        - assets/model/voice_analyzer.tflite

flutter_launcher_icons:
    android: true
    ios: true
    image_path: "assets/icon/logo.png"
    adaptive_icon_background: "#FFF1E6"
    adaptive_icon_foreground: "assets/icon/logo.png"

flutter_native_splash:
    color: "#5B8DEF"
    image: "assets/icon/logoo-splash.png"
    branding: "assets/icon/logoo-splash.png"
    android_12:
        color: "#5B8DEF"
        image: "assets/icon/logoo-splash.png"
        icon_background_color: "#5B8DEF"
